### ISSUE TITLE
Problem with torch_scatter

### ISSUE THREAD

**Issue by qianwenyuan** [benbogin/spider-schema-gnn#3]
Hi @benbogin 
 I tried to predict some queries. But when I run the predictor, I got an error:

 `Traceback (most recent call last):
  File "/home/qwy/anaconda3/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 100, in main
    import_submodules(package_name)
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/allennlp/common/util.py", line 314, in import_submodules
    module = importlib.import_module(package_name)
  File "/home/qwy/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./models/semantic_parsing/__init__.py", line 1, in <module>
    from models.semantic_parsing.spider_parser import SpiderParser
  File "./models/semantic_parsing/spider_parser.py", line 18, in <module>
    from torch_geometric.data import Data, Batch
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/torch_geometric/data/data.py", line 4, in <module>
    from torch_geometric.utils import (contains_isolated_nodes,
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/torch_geometric/utils/__init__.py", line 2, in <module>
    from .scatter import scatter_
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 1, in <module>
    import torch_scatter
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/qwy/anaconda3/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu`

`ImportError: /home/qwy/anaconda3/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE`

I still remember when I trained the models, I got the same problem with torch_scatter. But I just reinstalled torch_scatter and it worked. This time reinstalling doesn't work. Could you please help me?

**Comment by qianwenyuan** [comment]
i just fixed it. thx

**Comment by YaNjIeE** [comment]
Hi, I just got the same problem. Could you please tell me how to fix this? Thanks a lot.

**Comment by YaNjIeE** [comment]
@qianwenyuan

**Comment by benbogin** [comment]
I've seen this error before - it was a matter of the wrong combination of pytorch/torch-scatter versions.
Try uninstalling pytorch and all torch-scatter packagers, then re-installing it (1.1 should work) with the correct cuda version, and then re-installing torch-scatter - I believe this should help.

**Comment by YaNjIeE** [comment]
thanks a lot, I will give it a try :)

**Comment by patilaum** [comment]
Got the same error .please help

**Comment by qianwenyuan** [comment]
> Got the same error .please help

As Ben mentioned above, try reinstalling pytorch and torch-scatter and make sure the versions match。
