### ISSUE TITLE
AllenNLP "dataset_readers" module

### ISSUE THREAD

**Issue by abhisun** [benbogin/spider-schema-gnn#6]
Hello, 
My setup - Cuda 10, Ubuntu 18.04, Python 3.68, Docker container 

I followed all the instructions but, when I tried running the training command -
I get this below error.
Traceback (most recent call last):
  File "/opt/conda/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/opt/conda/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 100, in main
    import_submodules(package_name)
  File "/opt/conda/lib/python3.6/site-packages/allennlp/common/util.py", line 314, in import_submodules
    module = importlib.import_module(package_name)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'dataset_readers'**

Any ideas if this is a version compatibility issues?

**Comment by benbogin** [comment]
Hi,
It doesn't seem like a version issue. The modules from the repository aren't found - are you sure you ran this from main the directory of the repository?

**Comment by abhisun** [comment]
Yes, I put all the datasets, code and conda/python everything in one place and ran from that directory. It seems to be working now.
Thank you
